# Tipos de Distribuições Discretas

Para atender a situações mais práticas, é necessário expandir os conceitos relacionados a probabilidade de forma que tenhamos modelos probabilísticos que representem todos os tipos de variáveis. Neste capítulo trabalharemos com variáveis quantativas discretas.

> Exemplo (Bussab):

Chamamos de **variável aleatória discreta** uma função $X$ definida no espaço amostral $\Omega$ que assume valores em um conjunto de números finito.

Neste contexto vimos como associar a cada valor $x_i$ da variável aleatória $X$ a sua probabilidade de ocorrência. Matematicamente, escrevemos

Além disso, chamamos de **função de probabilidade** da variável aleatória discreta $X$ a função que a cada valor de $x_i$ associa a sua probabilidade de ocorrência

$$
p(x_i) = P(X=x_i) = p_i, i =1, 2, \dots
$$

## Valor Médio de uma Variável Aleatória

Dada uma variável aleatórai $X$ discreta, assumindo os valores \$x_1,\\dots, x_n\$, chamamos de valor médio ou esperança de $X$ o valor

$$
E[X] = \sum_{i=1}^n x_i P(X=x_i) = \sum_{i=1}^n x_i p_i.
$$

Chamamos de variância da variável aleatória $X$ o valor

$$
\text{var}[X] = \sum_{i=1}^n [x_i - E[X]]^2 p_i
$$
